extractor:
  url: "https://www.alphavantage.co/query"
  query_params:
    function: "DIGITAL_CURRENCY_DAILY"
  headers: ~
transformer: ~
writer:
  table: argos_finance_catalog.bronze.alpha_vantage_crypto_ohlcv
  fmt: iceberg
  mode: merge
  merge_columns: [id]
