extractor:
  url: "https://api.stlouisfed.org/fred/series/observations"
  query_params:
    series_id: "FEDFUNDS"
    file_type: "json"
  headers: ~

transformer: ~

writer:
  catalog: argos_finance_catalog
  schema: bronze 
  format: iceberg
  mode: append
  partition_by: load_prdt
  table: interest_rates
